obj-$(CONFIG_ESP32_WIFI)	+= main.o esp_cmd.o esp_wpa_utils.o esp_cfg80211.o esp_stats.o
obj-$(CONFIG_ESP32_BT)		+= esp_bt.o
obj-$(CONFIG_ESP32_WIFI_SPI)	+= esp_spi.o
obj-$(CONFIG_ESP32_WIFI_SDIO)	+= esp_sdio.o
